version: '3.4'
services:
    
  rasa-actions-server:
    image: rasa-bot:latest
    working_dir: /app
    build: "./"
    restart: always
    volumes:
    - ./actions:/app/actions
    command: ["rasa", "run", "actions"]
    ports:
    - '5055:5055'
    networks:
    - all
  
  rasa-server:
    image: rasa-bot:latest
    working_dir: /app
    build: "./"
    restart: always
    volumes:
    - ./actions:/app/actions
    - ./data:/app/data
    - ./models:/app/models
    command: bash -c "rasa run --enable-api --cors \"*\" --debug -p 5006"
    ports:
    - '5005:5006'
    networks:
    - all
  
 
networks:
  all:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
